version: '3'

tasks:
  check-venv:
    internal: true
    cmds:
      - |
        if ($null -eq $env:VIRTUAL_ENV) {
            Write-Host "Virtual environment not activated. Run venv/Scripts/activate first." -ForegroundColor Red
            exit 1
        }

  setup:
    desc: Set up development environment
    cmds:
      - python -m venv venv
      - powershell -File ./setup_env.ps1
      - venv\Scripts\Activate.ps1

  run-flask:
    desc: Run Flask application
    cmds:
      - python -m backend.src.app

  test:
    desc: Run all tests
    cmds:
      - python -m pytest tests -v --cov=src --cov-report=term-missing --mypy

  test-unit:
    desc: Run unit tests
    cmds:
      - python -m pytest tests/backend -v

  test-integration:
    desc: Run integration tests
    cmds:
      - python -m pytest tests/integration -v

  test-types:
    desc: Run type checking
    cmds:
      - python -m mypy src tests

  test-coverage:
    desc: Generate coverage report
    cmds:
      - python -m pytest tests -v --cov=src --cov-report=html
      - echo "Coverage report generated in htmlcov/index.html"

  test-watch:
    desc: Run tests in watch mode
    cmds:
      - python -m pytest-watch tests -- -v

  test-failed:
    desc: Rerun failed tests
    cmds:
      - python -m pytest tests -v --last-failed

  lint:
    desc: Run linting checks
    cmds:
      - task: test-types
      - python -m flake8 src tests
      - python -m black --check src tests
      - python -m isort --check-only src tests

  format:
    desc: Format code
    cmds:
      - python -m black src tests
      - python -m isort src tests

